### ISSUE TITLE
Add support for enablePaths LSP option

### ISSUE THREAD

**Issue by sgwilym** [sgwilym/nova-deno#21]
A new option was added in Deno 1.21 for path specific enabling: https://deno.com/blog/v1.21#enable-extension-in-subpaths-of-the-workspace

This would be fairly easy to add as a per-project setting.

**Comment by belcar-s** [comment]
How are the paths sent to the server? I wish this software were documented (or, if it is, that I could find the documentation) :slightly_frowning_face:. [I've seen a super mysterious `tsApi` be used](https://github.com/denoland/vscode_deno/blob/main/client/src/extension.ts#L257), but, since it's super mysterious, that hasn't really helped.

**Comment by sgwilym** [comment]
This would be an option we'd pass to the client upon initialisation, here: https://github.com/sgwilym/nova-deno/blob/main/src/client_disposable.ts#L119

**Comment by sgwilym** [comment]
This does indeed not yet work. :/ But I've opened an issue over at the Deno repo: https://github.com/denoland/deno/issues/19802

There's a possibility that the aggressive escaping which Nova's built-in LSP client does is messing with things.
