### ISSUE TITLE
Remove ability to send network requests?

### ISSUE THREAD

**Issue by atdrendel** [sgwilym/nova-deno#7]
Is there a reason why the extension needs to be able to [send network requests](https://github.com/sgwilym/nova-deno/blob/14feb7516d9c632fc058a1b26ecf4b1e80970f7e/deno.novaextension/extension.json#L16)?

**Comment by sgwilym** [comment]
@atdrendel I put this in here because this extension is able to send a 'cache' command which instructs Deno to cache all remote dependencies (and so triggering some network requests). But you've made me think that this is something Deno does rather than this extension, so maybe it's safe to remove this...?

**Comment by sgwilym** [comment]
As of v0.2 I've removed this entitlement as it doesn't seem this extension needs it to work. :)

**Comment by atdrendel** [comment]
Awesome. Thanks a lot for taking care of it, and thanks for working on this extension. I'm a big fan.
